# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you: 
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Your awesome title
email: your-email@example.com
description: >- # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: jekyllrb
github_username:  jekyll
name: Стилница

#URLs
contactform_server: https://simple-node-proxy.vercel.app
homepage: index.html

# Build settings
theme: minima
plugins:
  - jekyll-feed

exclude:
  - old.zip

collections_dir: _info

collections:
  # who are we
  people:
    output: true
    order:
      - antonia.html
  
  # books by our authors
  books:
    books: true
  
  # books we worked on
  # Books in swiper are shown by order, First item is in the center when the list is opened.
  # Items to the left are at the end of the list, items to the right are after the first item.
  # https://swiperjs.com/
  books-by-us:
    output: false
    order:
    - otlomkite.html
    - severnite.html
    - hagabula.html
    - ane.html
    - dancing-with-water.html
    - florence.html
    - hunter.html
    - inevitable.html
    - lotariqta-koritca.html
    - nevidimyat.html
    - our-history.html
    - pianist.html
    - prigotvi.html
    - rain.html
    - skippy.html
    - stories-with-horse.html
    - the-cat.html
    - vasdarzhatelyat.html
    - viet-tan.html
    - way.html
    - zebrata.html

  # testimonials
  testimonials:
    output: false

  events:
    output: true
  
  partners:
    output: false
    order:
     - redaktorite.html
     - zaeshka.html
     - atera.html
     - riba.html
     - zhenet45.html

  # our services
  services:
    output: true
    order:
      - consultation.html
      - reviewing.html
      - rewriting.html
      - editing.html
      - correcting.html
      - annotation.html
      - publishing.html

  process:
    output: true
    order:
      - how.html
      - concerns.html

  
  # information in displayed charts
  chart_info:
    output: false

defaults:
  - scope:
      type: "people"
    values:
      layout: "about-person"
  - scope:
      type: "services"
    values:
      layout: "our-services"
  - scope:
      type: "events"
    values:
      layout: "our-services"


# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
